import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import MainLayout from '../components/layout/MainLayout';
import NavBar from '../components/layout/NavBar';
import Button from '../components/ui/Button';
import EmptyState from '../components/ui/EmptyState';
import DigestCard from '../components/digest/DigestCard';
import { jobsData } from '../data/jobs';
import { calculateMatchScore } from '../utils/scoring';
import { Mail, Copy, Check, Sparkles, AlertCircle } from 'lucide-react';

const Digest = () => {
    const navigate = useNavigate();
    const [digest, setDigest] = useState(null);
    const [loading, setLoading] = useState(false);
    const [preferences, setPreferences] = useState(null);
    const [copied, setCopied] = useState(false);

    const todayDate = new Date().toISOString().split('T')[0];
    const storageKey = `jobTrackerDigest_${todayDate}`;

    useEffect(() => {
        // Load preferences
        const savedPrefs = localStorage.getItem('jobTrackerPreferences');
        if (savedPrefs) {
            setPreferences(JSON.parse(savedPrefs));
        }

        // Check for existing daily digest
        const existingDigest = localStorage.getItem(storageKey);
        if (existingDigest) {
            setDigest(JSON.parse(existingDigest));
        }
    }, [storageKey]);

    const generateDigest = () => {
        if (!preferences) return;

        setLoading(true);

        // Simulate "Processing" time for realism
        setTimeout(() => {
            // 1. Score all jobs
            const scoredJobs = jobsData.map(job => ({
                ...job,
                ...calculateMatchScore(job, preferences)
            }));

            // 2. Filter relevant jobs (Score > 0 to ensure basic relevance)
            const relevantJobs = scoredJobs.filter(job => job.score > 0);

            // 3. Sort by Score (Desc) then Freshness (Asc)
            relevantJobs.sort((a, b) => {
                if (b.score !== a.score) return b.score - a.score;
                return a.postedDaysAgo - b.postedDaysAgo;
            });

            // 4. Take top 10
            const top10 = relevantJobs.slice(0, 10);

            setDigest(top10);
            localStorage.setItem(storageKey, JSON.stringify(top10));
            setLoading(false);
        }, 800);
    };

    const handleCopy = () => {
        if (!digest) return;

        const text = digest.map((job, i) =>
            `${i + 1}. ${job.title} at ${job.company} (Score: ${job.score}%)\n${job.applyUrl}`
        ).join('\n\n');

        const header = `My 9AM Job Digest - ${todayDate}\n\n`;
        const footer = `\n\nGenerated by Job Notification Tracker`;

        navigator.clipboard.writeText(header + text + footer);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleEmail = () => {
        if (!digest) return;

        const subject = encodeURIComponent(`My 9AM Job Digest - ${todayDate}`);
        const body = digest.map((job, i) =>
            `${i + 1}. ${job.title} at ${job.company} (Score: ${job.score}%)\nApply: ${job.applyUrl}`
        ).join('\n\n');

        const mailtoLink = `mailto:?subject=${subject}&body=${encodeURIComponent(body)}`;
        window.open(mailtoLink, '_blank');
    };

    return (
        <MainLayout
            title="Daily Digest"
            description="Your curated morning briefing."
            header={<NavBar />}
        >
            <div className="max-w-4xl mx-auto">
                {!preferences ? (
                    <EmptyState
                        title="Preferences Required"
                        description="Please set your preferences to generate a personalized daily digest."
                        icon={AlertCircle}
                        actionLabel="Go to Settings"
                        onAction={() => navigate('/settings')}
                    />
                ) : !digest ? (
                    <div className="flex flex-col items-center justify-center py-20 bg-off-white border-2 border-dashed border-primary-text/10 rounded-lg">
                        <div className="bg-primary-text/5 p-4 rounded-full mb-6 relative">
                            <Sparkles size={48} className="text-primary-text/40" />
                            {loading && <div className="absolute inset-0 bg-white/50 animate-pulse rounded-full" />}
                        </div>
                        <h3 className="text-xl font-serif font-bold text-primary-text mb-2">
                            {loading ? "Analyzing Market..." : "Ready for your morning briefing?"}
                        </h3>
                        <p className="text-primary-text/60 max-w-md text-center mb-8 font-sans">
                            {loading
                                ? "We're scanning 60+ data points against your profile."
                                : "Generate a fresh list of your top 10 matched jobs for today."}
                        </p>
                        <Button
                            variant="primary"
                            onClick={generateDigest}
                            disabled={loading}
                            className="px-8 py-3"
                        >
                            {loading ? "Generating..." : "Generate Today's 9AM Digest (Simulated)"}
                        </Button>
                        <p className="mt-4 text-xs text-primary-text/30 font-mono">Demo Mode: Daily 9AM trigger simulated manually.</p>
                    </div>
                ) : digest.length === 0 ? (
                    <EmptyState
                        title="No Matches Today"
                        description="No jobs met your criteria today. Try broadening your preferences or checking back tomorrow."
                        icon={Mail}
                        actionLabel="Update Preferences"
                        onAction={() => navigate('/settings')}
                    />
                ) : (
                    <div className="animate-fade-in">
                        {/* Digest Header */}
                        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
                            <div>
                                <h2 className="text-2xl font-serif font-bold text-primary-text">Top 10 Jobs For You — 9AM Digest</h2>
                                <p className="text-primary-text/60 text-sm font-sans">{new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                            </div>
                            <div className="flex gap-3">
                                <Button variant="secondary" onClick={handleCopy} className="text-xs">
                                    {copied ? <Check size={14} className="mr-1" /> : <Copy size={14} className="mr-1" />}
                                    {copied ? "Copied" : "Copy to Clipboard"}
                                </Button>
                                <Button variant="secondary" onClick={handleEmail} className="text-xs">
                                    <Mail size={14} className="mr-1" />
                                    Email Draft
                                </Button>
                            </div>
                        </div>

                        {/* Digest List */}
                        <div className="space-y-2">
                            {digest.map((job, index) => (
                                <DigestCard key={job.id} job={job} index={index} />
                            ))}
                        </div>

                        {/* Digest Footer */}
                        <div className="mt-12 pt-8 border-t border-primary-text/10 text-center">
                            <p className="text-sm text-primary-text/40 font-serif italic">
                                This digest was generated based on your preferences. <br />
                                Next update available tomorrow at 9:00 AM.
                            </p>
                        </div>
                    </div>
                )}
            </div>
        </MainLayout>
    );
};

export default Digest;
