import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import MainLayout from '../components/layout/MainLayout';
import NavBar from '../components/layout/NavBar';
import Button from '../components/ui/Button';
import EmptyState from '../components/ui/EmptyState';
import DigestCard from '../components/digest/DigestCard';
import { jobsData } from '../data/jobs';
import { calculateMatchScore } from '../utils/scoring';
import { Mail, Copy, Check, Sparkles, AlertCircle, History, Clock } from 'lucide-react';
import Card from '../components/ui/Card';

const Digest = () => {
    const navigate = useNavigate();
    const [digest, setDigest] = useState(null);
    const [loading, setLoading] = useState(false);
    const [preferences, setPreferences] = useState(null);
    const [copied, setCopied] = useState(false);
    const [activityLog, setActivityLog] = useState([]);

    const todayDate = new Date().toISOString().split('T')[0];
    const storageKey = `jobTrackerDigest_${todayDate}`;

    useEffect(() => {
        const savedPrefs = localStorage.getItem('jobTrackerPreferences');
        if (savedPrefs) {
            setPreferences(JSON.parse(savedPrefs));
        }

        const existingDigest = localStorage.getItem(storageKey);
        if (existingDigest) {
            setDigest(JSON.parse(existingDigest));
        }

        const savedActivity = JSON.parse(localStorage.getItem('jobTrackerActivity') || '[]');
        setActivityLog(savedActivity);
    }, [storageKey]);

    const generateDigest = () => {
        if (!preferences) return;
        setLoading(true);
        setTimeout(() => {
            const scoredJobs = jobsData.map(job => ({ ...job, ...calculateMatchScore(job, preferences) }));
            const relevantJobs = scoredJobs.filter(job => job.score > 0);
            relevantJobs.sort((a, b) => {
                if (b.score !== a.score) return b.score - a.score;
                return a.postedDaysAgo - b.postedDaysAgo;
            });
            const top10 = relevantJobs.slice(0, 10);
            setDigest(top10);
            localStorage.setItem(storageKey, JSON.stringify(top10));
            setLoading(false);
        }, 800);
    };

    const handleCopy = () => {
        if (!digest) return;
        const text = digest.map((job, i) => `${i + 1}. ${job.title} at ${job.company} (Score: ${job.score}%)\n${job.applyUrl}`).join('\n\n');
        const header = `My 9AM Job Digest - ${todayDate}\n\n`;
        const footer = `\n\nGenerated by Job Notification Tracker`;
        navigator.clipboard.writeText(header + text + footer);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleEmail = () => {
        if (!digest) return;
        const subject = encodeURIComponent(`My 9AM Job Digest - ${todayDate}`);
        const body = digest.map((job, i) => `${i + 1}. ${job.title} at ${job.company} (Score: ${job.score}%)\nApply: ${job.applyUrl}`).join('\n\n');
        const mailtoLink = `mailto:?subject=${subject}&body=${encodeURIComponent(body)}`;
        window.open(mailtoLink, '_blank');
    };

    return (
        <MainLayout
            title="Daily Digest"
            description="Your curated morning briefing."
            header={<NavBar />}
        >
            <div className="max-w-4xl mx-auto space-y-12">
                {/* Digest Section */}
                <section>
                    {!preferences ? (
                        <EmptyState
                            title="Preferences Required"
                            description="Please set your preferences..."
                            icon={AlertCircle}
                            actionLabel="Go to Settings"
                            onAction={() => navigate('/settings')}
                        />
                    ) : !digest ? (
                        <div className="flex flex-col items-center justify-center p-12 bg-off-white border-2 border-dashed border-primary-text/10 rounded-lg">
                            {/* Loading State UI */}
                            <div className="bg-primary-text/5 p-4 rounded-full mb-6 relative">
                                <Sparkles size={32} className="text-primary-text/40" />
                                {loading && <div className="absolute inset-0 bg-white/50 animate-pulse rounded-full" />}
                            </div>
                            <h3 className="text-xl font-serif font-bold text-primary-text mb-4">Generate your briefing</h3>
                            <Button variant="primary" onClick={generateDigest} disabled={loading} className="px-8 py-3">
                                {loading ? "Generating..." : "Generate Today's 9AM Digest (Simulated)"}
                            </Button>
                        </div>
                    ) : digest.length === 0 ? (
                        <EmptyState title="No Matches" description="Try again tomorrow." icon={Mail} />
                    ) : (
                        <div className="animate-fade-in">
                            <div className="flex justify-between items-center mb-6">
                                <div>
                                    <h2 className="text-2xl font-serif font-bold text-primary-text">9AM Digest</h2>
                                    <p className="text-primary-text/60 text-sm">{todayDate}</p>
                                </div>
                                <div className="flex gap-2">
                                    <Button variant="secondary" onClick={handleCopy} className="text-xs">{copied ? <Check size={14} /> : <Copy size={14} />}</Button>
                                    <Button variant="secondary" onClick={handleEmail} className="text-xs"><Mail size={14} /></Button>
                                </div>
                            </div>
                            <div className="space-y-2">
                                {digest.map((job, index) => <DigestCard key={job.id} job={job} index={index} />)}
                            </div>
                        </div>
                    )}
                </section>

                {/* Recent Status Updates Section */}
                {activityLog.length > 0 && (
                    <section>
                        <div className="flex items-center gap-2 mb-4">
                            <History size={20} className="text-primary-text" />
                            <h2 className="text-xl font-serif font-bold text-primary-text">Recent Status Updates</h2>
                        </div>
                        <Card className="divide-y divide-primary-text/10">
                            {activityLog.map((log) => (
                                <div key={log.id} className="p-4 flex justify-between items-center hover:bg-primary-text/5 transition-colors">
                                    <div>
                                        <h4 className="font-bold text-sm text-primary-text">{log.jobTitle}</h4>
                                        <p className="text-xs text-primary-text/60">{log.company}</p>
                                    </div>
                                    <div className="text-right">
                                        <span className={`text-xs font-bold px-2 py-0.5 rounded border 
                                            ${log.status === 'Applied' ? 'text-blue-600 bg-blue-50 border-blue-100' :
                                                log.status === 'Rejected' ? 'text-red-600 bg-red-50 border-red-100' :
                                                    log.status === 'Selected' ? 'text-green-600 bg-green-50 border-green-100' : ''}
                                        `}>
                                            {log.status}
                                        </span>
                                        <div className="flex items-center justify-end gap-1 mt-1 text-xs text-primary-text/40">
                                            <Clock size={10} />
                                            {new Date(log.date).toLocaleDateString()}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </Card>
                    </section>
                )}
            </div>
        </MainLayout>
    );
};

export default Digest;
